### ISSUE TITLE
use yml new syntax to trigger release

### ISSUE THREAD

**Issue by tassioFront** [open-ish/utility#38]
use

```yml
on:
  push:
    branches:
      - master

```

instead

`  if: ${{ success() && (github.event_name != 'pull_request' || github.event.action == 'closed' && github.event.pull_request.merged == true) }}`

file: release-package.yml
